version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CORS_ORIGIN=https://werecooked.my.id,http://werecooked.my.id
      - MONGO_URI=mongodb://mongo:ylhJLGusxxhZcKarniyDYZyWwtFmxbxF@crossover.proxy.rlwy.net:50144
      - JWT_SECRET=5799f39d3045afe7aacdeac7e65888e53e1efb824b9c46a6c306dd5b71a89a488ada8049ec4c4736cb064877ea345c4c0b0449adad92e28124739351db7c2799
      - ML_API_BASE_URL=https://brohuy-recipes-recommendation-models.hf.space/
    expose:
      - "3000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app-network

  flask-api:
    build: ./flask-api
    container_name: flask-api
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - SECRET_KEY=e3b427cbd08cace80fca072c4c1b0db319d4be5a6799fecc092d10ebed30a7c9
      - AUTH_BACKEND_URL=http://backend:3000
      - JWT_SECRET_KEY=5799f39d3045afe7aacdeac7e65888e53e1efb824b9c46a6c306dd5b71a89a488ada8049ec4c4736cb064877ea345c4c0b0449adad92e28124739351db7c2799
      - JWT_ALGORITHM=HS256
      - MAX_RECOMMENDATIONS=50
      - DEFAULT_RECOMMENDATIONS=10
      - MODEL_PATH=./models/
      - NODE_API_URL=http://backend:3000/api
      - PORT=5000
      - LOG_LEVEL=INFO
    expose:
      - "5000"
    networks:
      - app-network

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - flask-api  # Tambahkan dependency ke flask-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge